"""
This program cleans the IDs passed as stdin, preparing them for use in
Blueprint. For example, if reads.txt is generated by a text editor,

  $ python raw-ids-to-blueprint.py < reads.txt > clean-reads.txt

Afterwards, upload clean-reads.txt to Blueprint, and then download the resulting
CSV file, which will contain all CNetIDs and names.
"""

import sys, re

print("".join(re.sub(r'([^0-9]|^)([0-9]{16})([^0-9]|$)',
                     r'%"\2^FIRST/LAST^0000000000000000000   000      ?;'
                     r'\2=00000000000000000?', x) for x in sys.stdin))
